# HEY! This file is used in the dbt-snowflake-query-tags integrations tests with GitHub Actions.
# You should __NEVER__ check credentials into version control. Thanks for reading :)

config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  target: snowflake
  outputs:
    snowflake:
      # type: snowflake
      # account: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_ACCOUNT') }}"
      # user: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_USER') }}"
      # password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD') }}"
      # role: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_ROLE') }}"
      # database: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_DATABASE') }}"
      # warehouse: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_TEST_WAREHOUSE') }}"
      # schema: dbt_snowflake_query_tags_test_commit_{{ env_var('GITHUB_SHA_OVERRIDE', '') if env_var('GITHUB_SHA_OVERRIDE', '') else env_var('GITHUB_SHA') }}
      # threads: 8
  
      snowflake:
        type: "snowflake"
        account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
        user: "{{ env_var('SNOWFLAKE_USER') }}"
        password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PASS') }}"
        role: "{{ env_var('SNOWFLAKE_ROLE') }}"
        database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
        warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
        schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
        threads: 10
