name: CI test package

on:
  workflow_dispatch:
  # all PRs, important to note that `pull_request_target` workflows
  # will run in the context of the target branch of a PR
  pull_request_target:

env:
  # These are configured in GitHub secrets
  DBT_PROFILES_DIR: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/integration_tests
  GITHUB_SHA_OVERRIDE: ${{ github.event.pull_request.head.sha }} # We need the commit hash of the pull request branch's head, the GITHUB_SHA env var is always the base branch in a pull_request_target trigger
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
  SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_TEST_USER }}
  DBT_ENV_SECRET_SNOWFLAKE_PASS: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_TEST_ROLE }}
  SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_TEST_DATABASE }}
  SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_TEST_WAREHOUSE }}
  SNOWFLAKE_SCHEMA: "integration_tests_snowflake_${{ github.run_number }}"


jobs:
  integration-snowflake:
    runs-on: ubuntu-latest
    environment:
      name: Approve Integration Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR

      - name: Install tox
        run: python3 -m pip install tox

      - name: Run Snowflake Tests
        run: tox -e snowflake
